package org.example.days;

import com.sun.jdi.connect.Connector;
import org.example.AbstractTest;
import org.example.Day08;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Stream;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.params.provider.Arguments.arguments;

public class Day08Test extends AbstractTest {
    public Day08Test() throws IOException, ClassNotFoundException {
        super(14);
//        setPartOneRealResult();
//        setExpectedExampleTwoResult();
//        setPartTwoRealResult();
    }

    static Stream<Arguments> partOneArgs() {
        return Stream.of(
                arguments("""
                        ..........
                        ...#......
                        ..........
                        ....a.....
                        ..........
                        .....a....
                        ..........
                        ......#...
                        ..........
                        ..........
                        """, 2),
                arguments("""
                        ..........
                        ...#......
                        #.........
                        ....a.....
                        ........a.
                        .....a....
                        ..#.......
                        ......#...
                        ..........
                        ..........
                        """, 4),
                arguments("""
                        ..........
                        ...#......
                        #.........
                        ....a.....
                        ........a.
                        .....a....
                        ..#.......
                        ......A...
                        ..........
                        ..........
                        """, 3),
                arguments("""
                        ......#....#
                        ...#....0...
                        ....#0....#.
                        ..#....0....
                        ....0....#..
                        .#....A.....
                        ...#........
                        #......#....
                        ........A...
                        .........A..
                        ..........#.
                        ..........#.
                        """, 14)
        );
    }

    @ParameterizedTest
    @MethodSource("partOneArgs")
    void partOneExamples(String map, long expectedAntinodes) {
        String[] arr = map.split("\n");
        List<String> lines = Arrays.asList(arr);
        Day08 day08 = new Day08(lines);
        long result = day08.partOne();
        assertEquals(expectedAntinodes, result);
    }

}
